package com.msp.enums;

public enum EAuditAction {
    REGISTRATION_SUBMITTED,
    REGISTRATION_APPROVED,
    REGISTRATION_REJECTED,
    TENANT_PROVISIONED,
    CONSENT_REQUESTED,
    CONSENT_GRANTED,
    CONSENT_REVOKED,
    ADMIN_DATA_ACCESS,
    TENANT_SUSPENDED,
    SUBSCRIPTION_CHANGED
}
