# ===== DEV (LOCAL MACHINE) =====
spring.application.name=MultiTenant SaaS POS System

server.port=5000
server.servlet.context-path=/msp

# Local Postgres (your PC / Docker)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

# Local Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis

# Actuator (keep for dev too)
management.endpoints.web.base-path=/actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true

# Swagger on in dev
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000