# Production-specific overrides
spring.datasource.url=jdbc:postgresql://pos-postgres-postgresql:5432/pos_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Redis
spring.data.redis.host=${REDIS_HOST:redis-service}
spring.data.redis.port=${REDIS_PORT:6379}

# Disable Swagger in production
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

# Production logging
logging.level.com.msp=WARN

# enable k8s-style probes
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true

# keep default base path
management.endpoints.web.base-path=/actuator

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true