spring.application.name=MultiTenant SaaS POS System
spring.datasource.url=jdbc:postgresql://localhost:5432/tenant_pos_sys
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
server.servlet.context-path=/msp

server.port=5000
