apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pos-backend
  namespace: pos
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: pos.185.229.227.70.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pos-backend
                port:
                  number: 80