apiVersion: v1
kind: Secret
metadata:
  name: pos-db-secret
  namespace: pos
type: Opaque
stringData:
  username: pos_sys
  password: olga
---
apiVersion: v1
kind: Secret
metadata:
  name: pos-backend-secrets
  namespace: pos
type: Opaque
stringData:
  jwt-secret: "639dc24e46cd4292e09bcffd6d0f475f7ee16b7c1a69f374509868f420c89626"